// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ingress.proto

package org.cloudfoundry.loggregator.v2;

public final class LoggregatorIngress {
  private LoggregatorIngress() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface IngressResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:loggregator.v2.IngressResponse)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code loggregator.v2.IngressResponse}
   */
  public  static final class IngressResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:loggregator.v2.IngressResponse)
      IngressResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use IngressResponse.newBuilder() to construct.
    private IngressResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private IngressResponse() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private IngressResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.cloudfoundry.loggregator.v2.LoggregatorIngress.internal_static_loggregator_v2_IngressResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.cloudfoundry.loggregator.v2.LoggregatorIngress.internal_static_loggregator_v2_IngressResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.cloudfoundry.loggregator.v2.LoggregatorIngress.IngressResponse.class, org.cloudfoundry.loggregator.v2.LoggregatorIngress.IngressResponse.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.cloudfoundry.loggregator.v2.LoggregatorIngress.IngressResponse)) {
        return super.equals(obj);
      }
      org.cloudfoundry.loggregator.v2.LoggregatorIngress.IngressResponse other = (org.cloudfoundry.loggregator.v2.LoggregatorIngress.IngressResponse) obj;

      boolean result = true;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.cloudfoundry.loggregator.v2.LoggregatorIngress.IngressResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.cloudfoundry.loggregator.v2.LoggregatorIngress.IngressResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.cloudfoundry.loggregator.v2.LoggregatorIngress.IngressResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.cloudfoundry.loggregator.v2.LoggregatorIngress.IngressResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.cloudfoundry.loggregator.v2.LoggregatorIngress.IngressResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.cloudfoundry.loggregator.v2.LoggregatorIngress.IngressResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.cloudfoundry.loggregator.v2.LoggregatorIngress.IngressResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.cloudfoundry.loggregator.v2.LoggregatorIngress.IngressResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.cloudfoundry.loggregator.v2.LoggregatorIngress.IngressResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.cloudfoundry.loggregator.v2.LoggregatorIngress.IngressResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.cloudfoundry.loggregator.v2.LoggregatorIngress.IngressResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.cloudfoundry.loggregator.v2.LoggregatorIngress.IngressResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.cloudfoundry.loggregator.v2.LoggregatorIngress.IngressResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code loggregator.v2.IngressResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:loggregator.v2.IngressResponse)
        org.cloudfoundry.loggregator.v2.LoggregatorIngress.IngressResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.cloudfoundry.loggregator.v2.LoggregatorIngress.internal_static_loggregator_v2_IngressResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.cloudfoundry.loggregator.v2.LoggregatorIngress.internal_static_loggregator_v2_IngressResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.cloudfoundry.loggregator.v2.LoggregatorIngress.IngressResponse.class, org.cloudfoundry.loggregator.v2.LoggregatorIngress.IngressResponse.Builder.class);
      }

      // Construct using org.cloudfoundry.loggregator.v2.LoggregatorIngress.IngressResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.cloudfoundry.loggregator.v2.LoggregatorIngress.internal_static_loggregator_v2_IngressResponse_descriptor;
      }

      public org.cloudfoundry.loggregator.v2.LoggregatorIngress.IngressResponse getDefaultInstanceForType() {
        return org.cloudfoundry.loggregator.v2.LoggregatorIngress.IngressResponse.getDefaultInstance();
      }

      public org.cloudfoundry.loggregator.v2.LoggregatorIngress.IngressResponse build() {
        org.cloudfoundry.loggregator.v2.LoggregatorIngress.IngressResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.cloudfoundry.loggregator.v2.LoggregatorIngress.IngressResponse buildPartial() {
        org.cloudfoundry.loggregator.v2.LoggregatorIngress.IngressResponse result = new org.cloudfoundry.loggregator.v2.LoggregatorIngress.IngressResponse(this);
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.cloudfoundry.loggregator.v2.LoggregatorIngress.IngressResponse) {
          return mergeFrom((org.cloudfoundry.loggregator.v2.LoggregatorIngress.IngressResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.cloudfoundry.loggregator.v2.LoggregatorIngress.IngressResponse other) {
        if (other == org.cloudfoundry.loggregator.v2.LoggregatorIngress.IngressResponse.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.cloudfoundry.loggregator.v2.LoggregatorIngress.IngressResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.cloudfoundry.loggregator.v2.LoggregatorIngress.IngressResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:loggregator.v2.IngressResponse)
    }

    // @@protoc_insertion_point(class_scope:loggregator.v2.IngressResponse)
    private static final org.cloudfoundry.loggregator.v2.LoggregatorIngress.IngressResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.cloudfoundry.loggregator.v2.LoggregatorIngress.IngressResponse();
    }

    public static org.cloudfoundry.loggregator.v2.LoggregatorIngress.IngressResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<IngressResponse>
        PARSER = new com.google.protobuf.AbstractParser<IngressResponse>() {
      public IngressResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new IngressResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<IngressResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<IngressResponse> getParserForType() {
      return PARSER;
    }

    public org.cloudfoundry.loggregator.v2.LoggregatorIngress.IngressResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface BatchSenderResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:loggregator.v2.BatchSenderResponse)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code loggregator.v2.BatchSenderResponse}
   */
  public  static final class BatchSenderResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:loggregator.v2.BatchSenderResponse)
      BatchSenderResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BatchSenderResponse.newBuilder() to construct.
    private BatchSenderResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BatchSenderResponse() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BatchSenderResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.cloudfoundry.loggregator.v2.LoggregatorIngress.internal_static_loggregator_v2_BatchSenderResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.cloudfoundry.loggregator.v2.LoggregatorIngress.internal_static_loggregator_v2_BatchSenderResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.cloudfoundry.loggregator.v2.LoggregatorIngress.BatchSenderResponse.class, org.cloudfoundry.loggregator.v2.LoggregatorIngress.BatchSenderResponse.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.cloudfoundry.loggregator.v2.LoggregatorIngress.BatchSenderResponse)) {
        return super.equals(obj);
      }
      org.cloudfoundry.loggregator.v2.LoggregatorIngress.BatchSenderResponse other = (org.cloudfoundry.loggregator.v2.LoggregatorIngress.BatchSenderResponse) obj;

      boolean result = true;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.cloudfoundry.loggregator.v2.LoggregatorIngress.BatchSenderResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.cloudfoundry.loggregator.v2.LoggregatorIngress.BatchSenderResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.cloudfoundry.loggregator.v2.LoggregatorIngress.BatchSenderResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.cloudfoundry.loggregator.v2.LoggregatorIngress.BatchSenderResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.cloudfoundry.loggregator.v2.LoggregatorIngress.BatchSenderResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.cloudfoundry.loggregator.v2.LoggregatorIngress.BatchSenderResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.cloudfoundry.loggregator.v2.LoggregatorIngress.BatchSenderResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.cloudfoundry.loggregator.v2.LoggregatorIngress.BatchSenderResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.cloudfoundry.loggregator.v2.LoggregatorIngress.BatchSenderResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.cloudfoundry.loggregator.v2.LoggregatorIngress.BatchSenderResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.cloudfoundry.loggregator.v2.LoggregatorIngress.BatchSenderResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.cloudfoundry.loggregator.v2.LoggregatorIngress.BatchSenderResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.cloudfoundry.loggregator.v2.LoggregatorIngress.BatchSenderResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code loggregator.v2.BatchSenderResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:loggregator.v2.BatchSenderResponse)
        org.cloudfoundry.loggregator.v2.LoggregatorIngress.BatchSenderResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.cloudfoundry.loggregator.v2.LoggregatorIngress.internal_static_loggregator_v2_BatchSenderResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.cloudfoundry.loggregator.v2.LoggregatorIngress.internal_static_loggregator_v2_BatchSenderResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.cloudfoundry.loggregator.v2.LoggregatorIngress.BatchSenderResponse.class, org.cloudfoundry.loggregator.v2.LoggregatorIngress.BatchSenderResponse.Builder.class);
      }

      // Construct using org.cloudfoundry.loggregator.v2.LoggregatorIngress.BatchSenderResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.cloudfoundry.loggregator.v2.LoggregatorIngress.internal_static_loggregator_v2_BatchSenderResponse_descriptor;
      }

      public org.cloudfoundry.loggregator.v2.LoggregatorIngress.BatchSenderResponse getDefaultInstanceForType() {
        return org.cloudfoundry.loggregator.v2.LoggregatorIngress.BatchSenderResponse.getDefaultInstance();
      }

      public org.cloudfoundry.loggregator.v2.LoggregatorIngress.BatchSenderResponse build() {
        org.cloudfoundry.loggregator.v2.LoggregatorIngress.BatchSenderResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.cloudfoundry.loggregator.v2.LoggregatorIngress.BatchSenderResponse buildPartial() {
        org.cloudfoundry.loggregator.v2.LoggregatorIngress.BatchSenderResponse result = new org.cloudfoundry.loggregator.v2.LoggregatorIngress.BatchSenderResponse(this);
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.cloudfoundry.loggregator.v2.LoggregatorIngress.BatchSenderResponse) {
          return mergeFrom((org.cloudfoundry.loggregator.v2.LoggregatorIngress.BatchSenderResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.cloudfoundry.loggregator.v2.LoggregatorIngress.BatchSenderResponse other) {
        if (other == org.cloudfoundry.loggregator.v2.LoggregatorIngress.BatchSenderResponse.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.cloudfoundry.loggregator.v2.LoggregatorIngress.BatchSenderResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.cloudfoundry.loggregator.v2.LoggregatorIngress.BatchSenderResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:loggregator.v2.BatchSenderResponse)
    }

    // @@protoc_insertion_point(class_scope:loggregator.v2.BatchSenderResponse)
    private static final org.cloudfoundry.loggregator.v2.LoggregatorIngress.BatchSenderResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.cloudfoundry.loggregator.v2.LoggregatorIngress.BatchSenderResponse();
    }

    public static org.cloudfoundry.loggregator.v2.LoggregatorIngress.BatchSenderResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BatchSenderResponse>
        PARSER = new com.google.protobuf.AbstractParser<BatchSenderResponse>() {
      public BatchSenderResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BatchSenderResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BatchSenderResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BatchSenderResponse> getParserForType() {
      return PARSER;
    }

    public org.cloudfoundry.loggregator.v2.LoggregatorIngress.BatchSenderResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SendResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:loggregator.v2.SendResponse)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code loggregator.v2.SendResponse}
   */
  public  static final class SendResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:loggregator.v2.SendResponse)
      SendResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SendResponse.newBuilder() to construct.
    private SendResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SendResponse() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SendResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.cloudfoundry.loggregator.v2.LoggregatorIngress.internal_static_loggregator_v2_SendResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.cloudfoundry.loggregator.v2.LoggregatorIngress.internal_static_loggregator_v2_SendResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.cloudfoundry.loggregator.v2.LoggregatorIngress.SendResponse.class, org.cloudfoundry.loggregator.v2.LoggregatorIngress.SendResponse.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.cloudfoundry.loggregator.v2.LoggregatorIngress.SendResponse)) {
        return super.equals(obj);
      }
      org.cloudfoundry.loggregator.v2.LoggregatorIngress.SendResponse other = (org.cloudfoundry.loggregator.v2.LoggregatorIngress.SendResponse) obj;

      boolean result = true;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.cloudfoundry.loggregator.v2.LoggregatorIngress.SendResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.cloudfoundry.loggregator.v2.LoggregatorIngress.SendResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.cloudfoundry.loggregator.v2.LoggregatorIngress.SendResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.cloudfoundry.loggregator.v2.LoggregatorIngress.SendResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.cloudfoundry.loggregator.v2.LoggregatorIngress.SendResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.cloudfoundry.loggregator.v2.LoggregatorIngress.SendResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.cloudfoundry.loggregator.v2.LoggregatorIngress.SendResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.cloudfoundry.loggregator.v2.LoggregatorIngress.SendResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.cloudfoundry.loggregator.v2.LoggregatorIngress.SendResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.cloudfoundry.loggregator.v2.LoggregatorIngress.SendResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.cloudfoundry.loggregator.v2.LoggregatorIngress.SendResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.cloudfoundry.loggregator.v2.LoggregatorIngress.SendResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.cloudfoundry.loggregator.v2.LoggregatorIngress.SendResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code loggregator.v2.SendResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:loggregator.v2.SendResponse)
        org.cloudfoundry.loggregator.v2.LoggregatorIngress.SendResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.cloudfoundry.loggregator.v2.LoggregatorIngress.internal_static_loggregator_v2_SendResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.cloudfoundry.loggregator.v2.LoggregatorIngress.internal_static_loggregator_v2_SendResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.cloudfoundry.loggregator.v2.LoggregatorIngress.SendResponse.class, org.cloudfoundry.loggregator.v2.LoggregatorIngress.SendResponse.Builder.class);
      }

      // Construct using org.cloudfoundry.loggregator.v2.LoggregatorIngress.SendResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.cloudfoundry.loggregator.v2.LoggregatorIngress.internal_static_loggregator_v2_SendResponse_descriptor;
      }

      public org.cloudfoundry.loggregator.v2.LoggregatorIngress.SendResponse getDefaultInstanceForType() {
        return org.cloudfoundry.loggregator.v2.LoggregatorIngress.SendResponse.getDefaultInstance();
      }

      public org.cloudfoundry.loggregator.v2.LoggregatorIngress.SendResponse build() {
        org.cloudfoundry.loggregator.v2.LoggregatorIngress.SendResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.cloudfoundry.loggregator.v2.LoggregatorIngress.SendResponse buildPartial() {
        org.cloudfoundry.loggregator.v2.LoggregatorIngress.SendResponse result = new org.cloudfoundry.loggregator.v2.LoggregatorIngress.SendResponse(this);
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.cloudfoundry.loggregator.v2.LoggregatorIngress.SendResponse) {
          return mergeFrom((org.cloudfoundry.loggregator.v2.LoggregatorIngress.SendResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.cloudfoundry.loggregator.v2.LoggregatorIngress.SendResponse other) {
        if (other == org.cloudfoundry.loggregator.v2.LoggregatorIngress.SendResponse.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.cloudfoundry.loggregator.v2.LoggregatorIngress.SendResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.cloudfoundry.loggregator.v2.LoggregatorIngress.SendResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:loggregator.v2.SendResponse)
    }

    // @@protoc_insertion_point(class_scope:loggregator.v2.SendResponse)
    private static final org.cloudfoundry.loggregator.v2.LoggregatorIngress.SendResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.cloudfoundry.loggregator.v2.LoggregatorIngress.SendResponse();
    }

    public static org.cloudfoundry.loggregator.v2.LoggregatorIngress.SendResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SendResponse>
        PARSER = new com.google.protobuf.AbstractParser<SendResponse>() {
      public SendResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SendResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SendResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SendResponse> getParserForType() {
      return PARSER;
    }

    public org.cloudfoundry.loggregator.v2.LoggregatorIngress.SendResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_loggregator_v2_IngressResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_loggregator_v2_IngressResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_loggregator_v2_BatchSenderResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_loggregator_v2_BatchSenderResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_loggregator_v2_SendResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_loggregator_v2_SendResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ringress.proto\022\016loggregator.v2\032\016envelop" +
      "e.proto\"\021\n\017IngressResponse\"\025\n\023BatchSende" +
      "rResponse\"\016\n\014SendResponse2\360\001\n\007Ingress\022G\n" +
      "\006Sender\022\030.loggregator.v2.Envelope\032\037.logg" +
      "regator.v2.IngressResponse\"\000(\001\022U\n\013BatchS" +
      "ender\022\035.loggregator.v2.EnvelopeBatch\032#.l" +
      "oggregator.v2.BatchSenderResponse\"\000(\001\022E\n" +
      "\004Send\022\035.loggregator.v2.EnvelopeBatch\032\034.l" +
      "oggregator.v2.SendResponse\"\000B5\n\037org.clou" +
      "dfoundry.loggregator.v2B\022LoggregatorIngr" +
      "essb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.cloudfoundry.loggregator.v2.LoggregatorEnvelope.getDescriptor(),
        }, assigner);
    internal_static_loggregator_v2_IngressResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_loggregator_v2_IngressResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_loggregator_v2_IngressResponse_descriptor,
        new java.lang.String[] { });
    internal_static_loggregator_v2_BatchSenderResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_loggregator_v2_BatchSenderResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_loggregator_v2_BatchSenderResponse_descriptor,
        new java.lang.String[] { });
    internal_static_loggregator_v2_SendResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_loggregator_v2_SendResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_loggregator_v2_SendResponse_descriptor,
        new java.lang.String[] { });
    org.cloudfoundry.loggregator.v2.LoggregatorEnvelope.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
